language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adrianoviana87/docker-kubernetes-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true adrianoviana87/docker-kubernetes-frontend yarn test
