language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adrianoviana87/docker-kubernetes-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true adrianoviana87/docker-kubernetes-frontend yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-kubernetes-frontend"
  env: "DockerKubernetesFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-788754165042"
  bucket_path: "docker-kubernetes-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
